### PR TITLE
Compare local and online schema.json in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
This PR does what its title says :)

### CODE REVIEW

**Comment by szepeviktor** [comment]
Now it runs on every PHP version.
Where could I move it?

**Comment by localheinz** [comment]
@szepeviktor 

Sorry for the delay, I will get back to you later!

**Review by localheinz — APPROVED** [review]

**Comment by localheinz** [comment]
Thank you, @szepeviktor!

**Comment by szepeviktor** [comment]
Actually **you** did the job.

**Pull request merged**
