### PR TITLE
Add support for PHP 8.0

### PR DESCRIPTION
**Pull request by core23**
This PR adds support for the upcoming PHP 8 release

### CODE REVIEW

**Comment by core23** [comment]
> array and string offset access syntax with curly braces is no longer supported

Looks like this is not yet possible :(

**Comment by localheinz** [comment]
@core23 

Thank you for your pull request! I will take a look later.

**Review by localheinz — APPROVED** [review]
👍

**Comment by localheinz** [comment]
Thank you, @core23!

**Comment by core23** [comment]
I wonder why composer could resolve this. There are some direct dependencies that do not have PHP 8 support 🤔 

- https://packagist.org/packages/ergebnis/json-normalizer
- https://packagist.org/packages/ergebnis/json-printer
- https://packagist.org/packages/localheinz/diff

**Comment by localheinz** [comment]
Ha, probably because of the platform configuration.  I will take a look later!

**Pull request merged**
