### PR TITLE
Enhancement: Require `ergebnis/json-normalizer:^4.0.0`

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] requires `ergebnis/json-normalizer:dev-main as 4.0.0`
- [x] adjusts class names

Related to #868.

### CODE REVIEW

**Comment by cafferata** [comment]
Hi @localheinz, I came to this issue because of the desire to use #868. I ran into the Composer constraint `ergebnis/json-normalizer`. So I've looked to see if someone already started an PR, and that's this PR. Can you tell me what you are still running into? Maybe some [upgrade steps](https://github.com/ergebnis/json-normalizer/blob/main/CHANGELOG.md#300) of the [ergebnis/json-normalizer](https://github.com/ergebnis/json-normalizer) [3.0.0 release](https://github.com/ergebnis/json-normalizer/releases/tag/3.0.0) haven't been implemented yet? Is there anything I might be able to help with? 🙏

**Comment by localheinz** [comment]
@cafferata 

Apologies for the delay, picking up the work here soon!

**Comment by cafferata** [comment]
No apologies necessary. ☺️

**Comment by localheinz** [comment]
Closing in favour of #1056.

**Pull request closed without merging**
