### PR TITLE
Update `composer-schema.json` file path

### LINKED ISSUE #254: Wrong schema file path
#### Steps required to reproduce the problem

1. `docker run -it php:alpine sh`
2. `cd /home/www-data`
3. `apk add composer`
4. `composer init`
    1. `Package name (<vendor>/<name>) [root/www-data]:` enter: `normalize/normalize`
    2. `Description []:` press enter
    3. `Author [, n to skip]:` enter: `n`
    4. `Minimum Stability []:` press enter
    5. `Package Type (e.g. library, project, metapackage, composer-plugin) []:` press enter
   6. `License []:` press enter
   7. `Would you like to define your dependencies (require) interactively [yes]?` enter: ` n`
    8. `Would you like to define your dev dependencies (require-dev) interactively [yes]?` press enter
    9. `Search for a package:` enter: `localheinz/composer-normalize`
    10.`Enter the version constraint to require (or leave blank to use the latest version):` press enter
    11. `Search for a package:` press enter
    12. `Do you confirm generation [yes]?` press enter
    13. `Would you like to install dependencies now [yes]?` press enter
5. `composer normalize` > Here is the error

#### Expected Result

The file should be found

#### Actual Result

Error because the file is not found :

> Schema URI "file:///usr/share/php/Composer/Json/../../../res/composer-schema.json" does not reference a document that could be read.

#### Additional informations

On my installation the file is located at:

> /usr/share/php/data/Composer/res/composer-schema.json

instead of:

> /usr/share/php/Composer/../../res/composer-schema.json

So i updated https://github.com/localheinz/composer-normalize/blob/abb9645a103238c84a06e7cfacb41c289ce09cd3/src/Command/SchemaUriResolver.php#L37

with the following change

```diff
- '%s/../../../res/composer-schema.json'
+ '%s/../../data/Composer/res/composer-schema.json'
```

### PR DESCRIPTION
**Pull request by homersimpsons**
Fixes #254

### CODE REVIEW

**Comment by localheinz** [comment]
@homersimpsons 

At the moment I am considering turning this project from a `composer` plugin into a stand-alone command-line tool, similar to how @icanhazstring has turned [`icanhazstring/composer-unused`](https://github.com/composer-unused/composer-unused) into a stand-aline command-line tool.

I believe this could solve a lot of problems, from

* #80 
* #207 
* #254 

What do you think?

**Comment by natanfelles** [comment]
Same issue here:
Captura de tela de 2019-12-17 17-03-28

I'm on Debian.

**Comment by localheinz** [comment]
Closing in favor of #273.

Released with [`2.0.1`](https://github.com/ergebnis/composer-normalize/releases/tag/2.0.1).

Thank you for your patience, @homersimpsons and @natanfelles - and apologies for the troubles!

**Comment by homersimpsons** [comment]
@localheinz a composer plugin might be a nice idea too. In fact once globally installed one can easily go through his projects to update them. (We have discussed some other options in #254 too)

**Pull request closed without merging**
